<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>de.vwgs</groupId>
  <artifactId>azubi-app</artifactId>
  <version>1.2</version>
  <packaging>war</packaging>

  <build>
    <finalName>app</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.4.0</version>
      </plugin>
    </plugins>
  </build>
</project>
