# Blue immer erreichbar
ProxyPass /app-blue http://127.0.0.1:8080/app-blue/
ProxyPassReverse /app-blue http://127.0.0.1:8080/app-blue/

# Green immer erreichbar
ProxyPass /app-green http://127.0.0.1:8080/app-green/
ProxyPassReverse /app-green http://127.0.0.1:8080/app-green/

# Live - muss zuletzt stehen
ProxyPass /app http://127.0.0.1:8080/app-green/
ProxyPassReverse /app http://127.0.0.1:8080/app-green/

